services:
  joy:
    image: husarion/teleop-twist-joy:humble-2.4.5-20240318
    container_name: joy
    build:
      context: .
      dockerfile: Dockerfile
    devices:
      - /dev/input
    volumes:
      - ./joy_params.yaml:/joy_params.yaml
    command: ros2 run joy joy_node --ros-args --params-file /joy_params.yaml
    tty: true
    hostname: joy
    # network_mode: host
    # ipc: host
    restart: always
    environment:
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
    
  teleop_twist_joy:
    image: husarion/teleop-twist-joy:humble-2.4.5-20240318
    container_name: teleop_twist_joy
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    command: ros2 run teleop_twist_joy teleop_node --ros-args --params-file /teleop_twist_joy_f710_params.yaml
    volumes:
      - ./teleop_twist_joy_f710_params.yaml:/teleop_twist_joy_f710_params.yaml
    tty: true
    hostname: teleop_twist_joy
    # network_mode: host
    # ipc: host
    restart: always
    environment:
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
  
  # New service for Bluetooth auto-connection and Docker restart
  # bt_auto_connect:
  #   image: husarnet/ros:bt_auto_connect
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.bt_auto_connect # Path to the Dockerfile for this service
  #   container_name: bt_auto_connect
  #   privileged: true # Grants the container all capabilities, essential for Bluetooth interaction (rfkill, bluetoothctl)
  #   network_mode: host # Allows the container to access the host's network stack directly, necessary for bluetoothctl and Docker socket access

  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock:rw  # Allow the container to control Docker on the host
  #     - /var/run/dbus:/var/run/dbus
  #     - ./docker_bt_auto_connect.py:/docker_bt_auto_connect.py
  #     # - ./audio:/usr/src/app/audio 
  #   # restart: always # Ensure this service is always running
    
  #   command: python3 /docker_bt_auto_connect.py # Command to execute your Python script

  # ktx_teleop_twist_joy:
  #   image: wonbot/shinheeagv:ktx_teleop_twist_joy_v.10
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.ktx_teleop_twist_joy
  #   volumes:
  #     - ./amr_ws/src/teleop_twist_joy/config/ps3.config.yaml:/ps3.config.yaml:rw
  #   command: 
  #     ros2 run teleop_twist_joy teleop_node --ros-args --params-file /ps3.config.yaml -r __node:=joystick_teleop 
  #     #ros2 run teleop_twist_joy teleop_node --ros-args --params-file /ps3.config.yaml

  #   container_name: ktx_teleop_twist_joy
    # tty: true
    # hostname: ktx_teleop_twist_joy
    # network_mode: host
    # ipc: host
    # restart: always
    # environment:
    #   - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp

  