ktx_joystick_teleop:
  ros__parameters:
    axis_linear:
      x: 1
      y: 0
    scale_linear:
      x: 0.35
      y: 0.35
    axis_angular:
      yaw: 3
    scale_angular:
      yaw: 0.3
    #require_enable_button: false
    enable_button: 5
    #enable_turbo_button: 8
    inverted_reverse : true

# sudo apt install joystick
# jstest /dev/input/js0