joystick_teleop:
  ros__parameters:
    axis_linear:
      x: 0
    scale_linear:
      x: 0.5
    # scale_linear_turbo:
    #   x: 1.5

    axis_angular:
      yaw: 3
    scale_angular:
      yaw: 1.0

    enable_button: 5  # L2 shoulder button
    #enable_turbo_button: 10  # L1 shoulder button
    inverted_reverse : true
  
# sudo apt install joystick
# jstest /dev/input/js0